/**
 * This file was automatically generated by `bwcx-client-vue`.
 * DO NOT MODIFY IT BY HAND.
 */

import { parseRoutes, RenderMethodKind } from 'bwcx-client-vue3';
import { DemoDetailRPO } from '../../common/modules/demo/demo.rpo';

const clientRoutes = parseRoutes([
  {
    name: 'About',
    path: '/about',
    fullPath: '/about',
    component: () => import(/* webpackChunkName: "About" */ '../modules/about/about.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: undefined,
    otherOptions: undefined,
  },
  {
    name: 'DemoDetail',
    path: '/demo/detail/:id',
    fullPath: '/demo/detail/:id',
    component: () => import(/* webpackChunkName: "DemoDetail" */ '../modules/demo/demo-detail.view.vue'),
    routeProps: DemoDetailRPO,
    priority: undefined,
    renderMethod: RenderMethodKind.SSR,
    otherOptions: undefined,
  },
  {
    name: 'Home',
    path: '/',
    fullPath: '/',
    component: () => import(/* webpackChunkName: "Home" */ '../modules/home/home.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: RenderMethodKind.SSR,
    otherOptions: undefined,
  },
]);

export default clientRoutes;

