/**
 * This file was automatically generated by `bwcx-client-vue`.
 * DO NOT MODIFY IT BY HAND.
 */

import { Newable } from 'bwcx-common';
import { RenderMethodKind } from 'bwcx-client-vue/enums';
import { DemoDetailRPO } from '../modules/demo/demo.rpo';

export const clientRoutesMap = new Map<string, { path: string; routeProps: Newable | undefined; renderMethod: RenderMethodKind | undefined }>([
  ['About', { path: '/about', routeProps: undefined, renderMethod: undefined }],
  ['DemoDetail', { path: '/demo/detail/:id', routeProps: DemoDetailRPO, renderMethod: RenderMethodKind.SSR }],
  ['Home', { path: '/', routeProps: undefined, renderMethod: RenderMethodKind.SSR }],
]);
export { DemoDetailRPO } from '../modules/demo/demo.rpo';
